version: '3.8'

services:
  db:
    image: postgres:17.5
    container_name: task_time_tracker_db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 6758
      POSTGRES_DB: task_time_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - general-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: slavyanin30/task_time_tracker:latest
    container_name: task_time_tracker_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_time_tracker
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 6758
      JWT_COOKIE_TOKEN_KEY: ${JWT_COOKIE_TOKEN_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - general-network

networks:
  general-network:
    driver: bridge

volumes:
  postgres_data: